export const INIT_APP = 'INIT_APP';

export const SET_ACTIVE_STACK = 'SET_ACTIVE_STACK';

export const ADD_FAVOURITE = 'ADD_FAVOURITE';
export const REMOVE_FAVOURITE = 'REMOVE_FAVOURITE';
export const FAVOURITE_CHANGED = 'FAVOURITE_CHANGED';
