export const SHOW_STACK_POPUP = 'SHOW_STACK_POPUP';
export const HIDE_STACK_POPUP = 'HIDE_STACK_POPUP';

export const ADD_STACK_TO_FAVOURITES = 'ADD_STACK_TO_FAVOURITES';
export const REMOVE_STACK_FROM_FAVOURITES = 'REMOVE_STACK_FROM_FAVOURITES';

export const ENABLE_SCROLL = 'ENABLE_SCROLL';
export const DISABLE_SCROLL = 'DISABLE_SCROLL';
